sudo: required
services:
  - docker

before_install:
  - docker build -t eugenewcf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eugenewcf/react-test npm test -- --coverage

after_success:
  - docker build -t eugenewcf/multi-client ./client
  - docker build -t eugenewcf/multi-nginx ./nginx
  - docker build -t eugenewcf/multi-server ./server
  - docker build -t eugenewcf/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images an push them to docker hub
  - docker push eugenewcf/multi-client
  - docker push eugenewcf/multi-nginx
  - docker push eugenewcf/multi-server
  - docker push eugenewcf/multi-worker